### ISSUE TITLE
Instruction families TODO

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#777]
- [x] KEC
- [x] CONTEXT (easy?)
- [x] ACCOUNT (easy?)
- [x] COPY 
  - [x] CODECOPY
  - [x] EXTCODECOPY
  - [x] CALLDATACOPY
  - [x] RETURNDATACOPY
- [x] TRANSACTION
- [x] BLOCK (easy?)
- [x] STACKRAM
- [x] STORAGE
  - [x] SSTORE
  - [x] SLOAD
- [x] JUMP
- [x] MACHINESTATE (easy?)
- [x] PUSHPOP
- [x] DUP
- [x] SWAP
- [x] LOGX
- [ ] CREATE
- [ ] CALL
  - [ ] common unexceptional sub-section
  - [ ] optional precompile sub-section
  - [ ] the "splitting" of the CALL section (the CALL instruction part + the precompile part)
  - [ ] the "merging" of those when it comes to tracing
- [ ] HALT
    - [x] STOP
    - [ ] RETURN @OlivierBBB 
    - [x] REVERT @lorenzogentile404 
    - [ ] SELFDESTRUCT
      - [ ] implement MARKED_FOR_SELFDESTRUCT bit
- [x] INVALID

**Comment by letypequividelespoubelles** [comment]
review when we trigger the MMU : https://github.com/Consensys/linea-arithmetization/issues/810

**Comment by letypequividelespoubelles** [comment]
done
